
// Objective-C API for talking to the following Go packages
//
//	scalecloud
//
// File is generated by gomobile bind. Do not edit.
#ifndef __ScaleCloudGo_FRAMEWORK_H__
#define __ScaleCloudGo_FRAMEWORK_H__

#include "ScaleCloudGo.objc.h"
#include "Universe.objc.h"

#endif
