# SPDX-FileCopyrightText: 2024 Next-cloud GmbH and Next-cloud contributors
# SPDX-License-Identifier: GPL-3.0-or-later
# You can add one username per supported platform and one custom link
custom: https://nextcloud.com/include/
