name: ScaleCloudGo
targets:
  ScaleCloudGo:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    settings:
      SKIP_INSTALL: "NO"
      BUILD_LIBRARY_FOR_DISTRIBUTION: "YES"
      DEFINES_MODULE: "YES"
      PRODUCT_MODULE_NAME: "ScaleCloudGo"
    buildPhases:
      - script: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          gomobile bind -target=ios/arm64 -o "$BUILT_PRODUCTS_DIR/ScaleCloudGo.framework" "$PROJECT_DIR"
        name: Build Go Framework
