// SPDX-FileCopyrightText: Nextcloud GmbH
// SPDX-FileCopyrightText: 2024 Marino Faggiana
// SPDX-License-Identifier: GPL-3.0-or-later

import Foundation
@preconcurrency import Alamofire

public struct NKSession: Sendable {
    public var urlBase: String
    public var user: String
    public var userId: String
    public var password: String
    public var account: String
    public var userAgent: String
    public let groupIdentifier: String
    public let httpMaximumConnectionsPerHost: Int
    public let httpMaximumConnectionsPerHostInDownload: Int
    public let httpMaximumConnectionsPerHostInUpload: Int
    public let dav: String = "remote.php/dav"
    public var sharedCookieStorage = ""
    public let sessionData: Alamofire.Session
    public let sessionDataNoCache: Alamofire.Session
    public let sessionDownloadBackground: URLSession
    public let backgroundSessionDelegate: URLSessionDelegate?
    public let sessionUploadBackground: URLSession
    public let sessionUploadBackgroundWWan: URLSession

    // ScaleCloud: stored so lazy vars can access it after init() completes
    public let proxyDictionary: [AnyHashable: Any]?
    
    // ScaleCloud: lifecycle tracking — analogous to static fields in OwnCloudClient.java
    private class WeakURLSession {
        weak var value: URLSession?
        init(_ value: URLSession) { self.value = value }
    }
    private static var proxyClients: [WeakURLSession] = []
    private static var cleanupTimer: Timer? = nil
    private static var proxyPort: Int = 0
    private static let lock = NSLock()

    // ScaleCloud: analogous to applyProxySettings() in OwnCloudClient.java
    // Called from init(), starts (or reuses) the proxy, returns the proxy dictionary.
    // Calls directly into the Go framework generated by gomobile bind from scalecloud-ios/bridge.go.
    private static func applyProxySettings() -> [AnyHashable: Any]? {
        lock.lock()
        defer { lock.unlock() }
        if proxyPort == 0 {
            // Match Android exactly: <app files dir>/tailscale
            let baseURL = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
            let stateDirURL = baseURL.appendingPathComponent("tailscale", isDirectory: true)
            let stateDir = stateDirURL.path

            do {
                try FileManager.default.createDirectory(at: stateDirURL, withIntermediateDirectories: true)
            } catch {
                nkLog(error: "ScaleCloud: failed to create state directory: \(error)")
            }

            // Call into the Go framework produced by gomobile bind.
            // The module name comes from the Go package ("scalecloud" → usually "Scalecloud").
            do {
                proxyPort = try Scalecloud.startProxy("ios-scalecloud-client", stateDir)
            } catch {
                nkLog(error: "ScaleCloud: startProxy failed: \(error)")
                proxyPort = 0
            }
        }
        guard proxyPort > 0 else {
            nkLog(error: "ScaleCloud: proxy failed to start, Tailscale addresses will be unreachable")
            return nil
        }
        return [
            kCFNetworkProxiesHTTPEnable: true,
            kCFNetworkProxiesHTTPProxy: "127.0.0.1",
            kCFNetworkProxiesHTTPPort: proxyPort,
            kCFNetworkProxiesHTTPSEnable: true,
            kCFNetworkProxiesHTTPSProxy: "127.0.0.1",
            kCFNetworkProxiesHTTPSPort: proxyPort
        ]
    }

    // ScaleCloud: analogous to the scheduled cleanup in OwnCloudClient.java
    private static func checkAndCleanup() {
        lock.lock()
        defer { lock.unlock() }
        proxyClients.removeAll { $0.value == nil }
        if proxyClients.isEmpty {
            do {
                try Scalecloud.stopProxy()
            } catch {
                nkLog(error: "ScaleCloud: stopProxy failed: \(error)")
            }
            proxyPort = 0
            cleanupTimer?.invalidate()
            cleanupTimer = nil
        }
    }

    // ScaleCloud: register a URLSession so we can track when all sessions are gone
    private static func registerSession(_ session: URLSession) {
        lock.lock()
        defer { lock.unlock() }
        proxyClients.append(WeakURLSession(session))

        if cleanupTimer == nil {
            // Check every 60 seconds (more aggressive than Android's 5 minutes for iOS)
            cleanupTimer = Timer.scheduledTimer(withTimeInterval: 60, repeats: true) { _ in
                checkAndCleanup()
            }
        }
    }

    public lazy var sessionDownloadBackgroundExt: URLSession = {
        let config = URLSessionConfiguration.background(withIdentifier: NKCommon().identifierSessionDownloadBackgroundExt)
        config.sharedContainerIdentifier = groupIdentifier
        config.sessionSendsLaunchEvents = true
        config.isDiscretionary = false
        config.allowsCellularAccess = true
        config.requestCachePolicy = .useProtocolCachePolicy
        config.httpMaximumConnectionsPerHost = httpMaximumConnectionsPerHostInDownload
        config.httpCookieStorage = HTTPCookieStorage.sharedCookieStorage(forGroupContainerIdentifier: sharedCookieStorage)
        #if os(iOS) || targetEnvironment(macCatalyst)
        config.multipathServiceType = .handover
        #endif
        config.connectionProxyDictionary = proxyDictionary
        return URLSession(configuration: config, delegate: backgroundSessionDelegate, delegateQueue: .main)
    }()

    public lazy var sessionUploadBackgroundExt: URLSession = {
        let config = URLSessionConfiguration.background(withIdentifier: NKCommon().identifierSessionUploadBackgroundExt)
        config.sharedContainerIdentifier = groupIdentifier
        config.sessionSendsLaunchEvents = true
        config.isDiscretionary = false
        config.allowsCellularAccess = true
        config.requestCachePolicy = .useProtocolCachePolicy
        config.httpMaximumConnectionsPerHost = httpMaximumConnectionsPerHostInUpload
        config.httpCookieStorage = HTTPCookieStorage.sharedCookieStorage(forGroupContainerIdentifier: sharedCookieStorage)
        #if os(iOS) || targetEnvironment(macCatalyst)
        config.multipathServiceType = .handover
        #endif
        config.connectionProxyDictionary = proxyDictionary
        return URLSession(configuration: config, delegate: backgroundSessionDelegate, delegateQueue: .main)
    }()

    init(nkCommonInstance: NKCommon,
         urlBase: String,
         user: String,
         userId: String,
         password: String,
         account: String,
         userAgent: String,
         groupIdentifier: String,
         httpMaximumConnectionsPerHost: Int,
         httpMaximumConnectionsPerHostInDownload: Int,
         httpMaximumConnectionsPerHostInUpload: Int) {
        self.urlBase = urlBase
        self.user = user
        self.userId = userId
        self.password = password
        self.account = account
        self.userAgent = userAgent
        self.groupIdentifier = groupIdentifier
        self.httpMaximumConnectionsPerHost = httpMaximumConnectionsPerHost
        self.httpMaximumConnectionsPerHostInDownload = httpMaximumConnectionsPerHostInDownload
        self.httpMaximumConnectionsPerHostInUpload = httpMaximumConnectionsPerHostInUpload
        self.backgroundSessionDelegate = NKBackground(nkCommonInstance: nkCommonInstance)

        // Strange but works ?!?!
        sharedCookieStorage = user + "@" + urlBase

        // ScaleCloud: start proxy first, before any sessions are built
        // Analogous to OwnCloudClient constructor calling applyProxySettings() first
        self.proxyDictionary = NKSession.applyProxySettings()


        // SessionData Alamofire
        let configurationSessionData = URLSessionConfiguration.af.default
        configurationSessionData.requestCachePolicy = .useProtocolCachePolicy
        configurationSessionData.httpMaximumConnectionsPerHost = httpMaximumConnectionsPerHost

        #if os(iOS) || targetEnvironment(macCatalyst)
        configurationSessionData.multipathServiceType = .handover
        #endif

        configurationSessionData.httpCookieStorage = HTTPCookieStorage.sharedCookieStorage(forGroupContainerIdentifier: sharedCookieStorage)
        configurationSessionData.connectionProxyDictionary = self.proxyDictionary
        sessionData = Alamofire.Session(configuration: configurationSessionData,
                                        delegate: NextcloudKitSessionDelegate(nkCommonInstance: nkCommonInstance),
                                        rootQueue: nkCommonInstance.rootQueue,
                                        requestQueue: nkCommonInstance.requestQueue,
                                        serializationQueue: nkCommonInstance.serializationQueue,
                                        eventMonitors: [NKMonitor(nkCommonInstance: nkCommonInstance)])
        NKSession.registerSession(sessionData.session)

        // SessionDataNoCache Alamofire
        let configurationSessionDataNoCache = URLSessionConfiguration.af.default
        configurationSessionDataNoCache.connectionProxyDictionary = proxyDictionary
        configurationSessionDataNoCache.requestCachePolicy = .reloadIgnoringLocalAndRemoteCacheData
        configurationSessionDataNoCache.httpMaximumConnectionsPerHost = httpMaximumConnectionsPerHost
        configurationSessionDataNoCache.httpCookieStorage = HTTPCookieStorage.sharedCookieStorage(forGroupContainerIdentifier: sharedCookieStorage)

        sessionDataNoCache = Alamofire.Session(configuration: configurationSessionDataNoCache,
                                               delegate: NextcloudKitSessionDelegate(nkCommonInstance: nkCommonInstance),
                                               rootQueue: nkCommonInstance.rootQueue,
                                               requestQueue: nkCommonInstance.requestQueue,
                                               serializationQueue: nkCommonInstance.serializationQueue,
                                               eventMonitors: [NKMonitor(nkCommonInstance: nkCommonInstance)])
        NKSession.registerSession(sessionDataNoCache.session)

        // Session Download Background
        let configurationDownloadBackground = URLSessionConfiguration.background(withIdentifier: NKCommon().getSessionConfigurationIdentifier(NKCommon().identifierSessionDownloadBackground, account: account))
        configurationDownloadBackground.connectionProxyDictionary = proxyDictionary
        configurationDownloadBackground.allowsCellularAccess = true

        if #available(macOS 11, *) {
            configurationDownloadBackground.sessionSendsLaunchEvents = true
        }

        configurationDownloadBackground.isDiscretionary = false
        configurationDownloadBackground.httpMaximumConnectionsPerHost = self.httpMaximumConnectionsPerHostInDownload
        configurationDownloadBackground.requestCachePolicy = .useProtocolCachePolicy

        #if os(iOS) || targetEnvironment(macCatalyst)
            configurationDownloadBackground.multipathServiceType = .handover
        #endif

        configurationDownloadBackground.httpCookieStorage = HTTPCookieStorage.sharedCookieStorage(forGroupContainerIdentifier: sharedCookieStorage)
        sessionDownloadBackground = URLSession(configuration: configurationDownloadBackground, delegate: backgroundSessionDelegate, delegateQueue: OperationQueue.main)
        NKSession.registerSession(sessionDownloadBackground)

        // Session Upload Background
        let configurationUploadBackground = URLSessionConfiguration.background(withIdentifier: NKCommon().getSessionConfigurationIdentifier(NKCommon().identifierSessionUploadBackground, account: account))
        configurationUploadBackground.connectionProxyDictionary = proxyDictionary
        configurationUploadBackground.allowsCellularAccess = true

        if #available(macOS 11, *) {
            configurationUploadBackground.sessionSendsLaunchEvents = true
        }

        configurationUploadBackground.isDiscretionary = false
        configurationUploadBackground.httpMaximumConnectionsPerHost = self.httpMaximumConnectionsPerHostInUpload
        configurationUploadBackground.requestCachePolicy = .useProtocolCachePolicy

        #if os(iOS) || targetEnvironment(macCatalyst)
            configurationUploadBackground.multipathServiceType = .handover
        #endif

        configurationUploadBackground.httpCookieStorage = HTTPCookieStorage.sharedCookieStorage(forGroupContainerIdentifier: sharedCookieStorage)
        sessionUploadBackground = URLSession(configuration: configurationUploadBackground, delegate: backgroundSessionDelegate, delegateQueue: OperationQueue.main)
        NKSession.registerSession(sessionUploadBackground)

        // Session Upload Background WWan
        let configurationUploadBackgroundWWan = URLSessionConfiguration.background(withIdentifier: NKCommon().getSessionConfigurationIdentifier(NKCommon().identifierSessionUploadBackgroundWWan, account: account))
        configurationUploadBackgroundWWan.connectionProxyDictionary = proxyDictionary
        configurationUploadBackgroundWWan.allowsCellularAccess = false

        if #available(macOS 11, *) {
            configurationUploadBackgroundWWan.sessionSendsLaunchEvents = true
        }

        configurationUploadBackgroundWWan.isDiscretionary = false
        configurationUploadBackgroundWWan.httpMaximumConnectionsPerHost = self.httpMaximumConnectionsPerHostInUpload
        configurationUploadBackgroundWWan.requestCachePolicy = .useProtocolCachePolicy
        configurationUploadBackgroundWWan.httpCookieStorage = HTTPCookieStorage.sharedCookieStorage(forGroupContainerIdentifier: sharedCookieStorage)
        sessionUploadBackgroundWWan = URLSession(configuration: configurationUploadBackgroundWWan, delegate: backgroundSessionDelegate, delegateQueue: OperationQueue.main)
        NKSession.registerSession(sessionUploadBackgroundWWan)
    }
}
