name: ScaleCloudKitProject
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "14.0"
targets:
  ScaleCloudKit:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources
    dependencies:
      - framework: ../SCGo.xcframework
