// Objective-C API for talking to scalecloud Go package.
//   gobind -lang=objc scalecloud
//
// File is generated by gobind. Do not edit.

#ifndef __SCGo_H__
#define __SCGo_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT BOOL SCGoStartProxy(NSString* _Nullable hostname, NSString* _Nullable stateDir, long* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL SCGoStopProxy(NSError* _Nullable* _Nullable error);

#endif
