
// Objective-C API for talking to the following Go packages
//
//	scalecloud
//
// File is generated by gomobile bind. Do not edit.
#ifndef __SCGo_FRAMEWORK_H__
#define __SCGo_FRAMEWORK_H__

#include "SCGo.objc.h"
#include "Universe.objc.h"

#endif
