name: ScaleCloudWrap
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "14.0"
targets:
  Wrapper:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources
    dependencies:
      - target: ScaleCloudApp
projectReferences:
  ScaleCloudApp:
    path: ../ScaleCloudApp/ScaleCloudApp.xcodeproj
