name: Get macOS libimobiledevice binaries ARM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install libimobiledevice
        run: brew install libimobiledevice

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: libimobiledevice-macos
          path: |
            /opt/homebrew/bin/idevicedebug
            /opt/homebrew/bin/ideviceimagemounter
            /opt/homebrew/bin/ideviceinfo
