name: Get Windows libimobiledevice binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install libimobiledevice via MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-libimobiledevice

      - name: Copy binaries
        shell: msys2 {0}
        run: |
          cp /mingw64/bin/idevicedebug.exe idevicedebug.exe
          cp /mingw64/bin/ideviceimagemounter.exe ideviceimagemounter.exe
          cp /mingw64/bin/ideviceinfo.exe ideviceinfo.exe

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: libimobiledevice-windows-x86_64
          path: |
            idevicedebug.exe
            ideviceimagemounter.exe
            ideviceinfo.exe
