name: Get Linux libimobiledevice binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install libimobiledevice
        run: sudo apt-get install -y libimobiledevice-utils

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: libimobiledevice-linux-x86_64
          path: |
            /usr/bin/idevicedebug
            /usr/bin/ideviceimagemounter
            /usr/bin/ideviceinfo
